In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
from scipy.stats import linregress, pearsonr
import plotly.express as px
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [3]:
player_passing_1 = pd.read_csv('players/player_premier_league_passing_type.csv')
player_passing_2 = pd.read_csv('players/player_premier_league_passing.csv')

In [4]:
player_passing_1.head()

,Unnamed: 0,Player,Nation,Pos,Squad,Age,90s_played,TotalAtt_Pass,TotalComp_Passes,Pass_Blocked,Live_Passes,Dead_Passes,Switches_Pass,Cross_Passes
0,0,Brenden Aaronson,us USA,"MF,FW",Leeds United,21,26.4,797,592,27,711,85,2,72
1,1,George Abbott,eng ENG,MF,Tottenham,16,0.0,1,1,0,1,0,0,0
2,2,Che Adams,sct SCO,FW,Southampton,26,22.1,498,330,17,490,7,7,12
3,3,Tyler Adams,us USA,MF,Leeds United,23,24.0,1343,1108,24,1271,72,2,2
4,4,Tosin Adarabioyo,eng ENG,DF,Fulham,24,23.2,1300,1066,10,1235,58,12,2

In [5]:
player_passing_2.head()

,Unnamed: 0,Player,Nation,Pos,Squad,Age,90s_played,TotalComp_Passes,TotalAtt_Pass,TotalPas_Rate,...,LongPasses_Att,Assist,xAG,xA,Ast-xAG,KeyPas,PassinF3rd,PassinPen,CrossPasinPen,ProgPass
0,0,Brenden Aaronson,us USA,"MF,FW",Leeds United,21,26.4,592,797,74.3,...,65,3,4.2,2.6,-1.2,46,47,16,4,86
1,1,George Abbott,eng ENG,MF,Tottenham,16,0.0,1,1,100.0,...,0,0,0.0,0.0,0.0,0,0,0,0,0
2,2,Che Adams,sct SCO,FW,Southampton,26,22.1,330,498,66.3,...,37,3,2.8,2.2,0.2,24,21,11,2,34
3,3,Tyler Adams,us USA,MF,Leeds United,23,24.0,1108,1343,82.5,...,107,0,1.4,1.0,-1.4,24,110,13,0,136
4,4,Tosin Adarabioyo,eng ENG,DF,Fulham,24,23.2,1066,1300,82.0,...,223,0,0.4,0.5,-0.4,6,96,7,0,95

In [16]:
common_cols = player_passing_1.columns.intersection(player_passing_2.columns).tolist()
player_passing = pd.merge(player_passing_1, player_passing_2, on=common_cols)
player_passing = player_passing.drop(columns=['Unnamed: 0'])
player_passing.index = player_passing.index + 1
player_passing.head()

,Player,Nation,Pos,Squad,Age,90s_played,TotalAtt_Pass,TotalComp_Passes,Pass_Blocked,Live_Passes,...,LongPasses_Att,Assist,xAG,xA,Ast-xAG,KeyPas,PassinF3rd,PassinPen,CrossPasinPen,ProgPass
1,Brenden Aaronson,us USA,"MF,FW",Leeds United,21,26.4,797,592,27,711,...,65,3,4.2,2.6,-1.2,46,47,16,4,86
2,George Abbott,eng ENG,MF,Tottenham,16,0.0,1,1,0,1,...,0,0,0.0,0.0,0.0,0,0,0,0,0
3,Che Adams,sct SCO,FW,Southampton,26,22.1,498,330,17,490,...,37,3,2.8,2.2,0.2,24,21,11,2,34
4,Tyler Adams,us USA,MF,Leeds United,23,24.0,1343,1108,24,1271,...,107,0,1.4,1.0,-1.4,24,110,13,0,136
5,Tosin Adarabioyo,eng ENG,DF,Fulham,24,23.2,1300,1066,10,1235,...,223,0,0.4,0.5,-0.4,6,96,7,0,95